services:
  app:
    image: python:3.9.17
    working_dir: /app    
    command: |-
      bash -c
      pip install poetry && 
      poetry config virtualenvs.create false && 
      poetry install --only main --no-root --no-directory && 
      rm -rf ~/.cache/pypoetry/ && 
      uvicorn src.app:app --host 0.0.0.0 --port 8000"
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./:/app
      - sqlite_db:/app/.sqlite

volumes:
  sqlite_db: